### ISSUE TITLE
`some` and `many` are named the opposite than the Haskell Alternative functions

### ISSUE THREAD

**Issue by hagl** [stew/codebase#7]
The parsers have following semantic:
`some : Parser e t a -> Parser e t [a]` : matches zero or more
`many : Parser e t a -> Parser e t [a]` : matches one or more

while in Haskell the functions of [`Alternative`](https://hackage.haskell.org/package/base-4.16.0.0/docs/Control-Applicative.html#g:2) from `Control.Applicative` have

`some :: f a -> f [a]` : One or more.
`many :: f a -> f [a]` : Zero or more.

I'm trying to port a Megaparsec parser and got confused by this names more than once.

I was also wondering if it makes sense to express the difference in the types by using `Nonempty` instead of `List` for the one that must match at lease onces, e.g. have

`many : Parser e t a -> Parser e t [a]`
`some : Parser e t a -> Parser e t (Nonempty a)`

What do you think?

**Comment by hagl** [comment]
![image](https://user-images.githubusercontent.com/1162118/144403492-ba34f67d-dac8-48bd-afa5-0011409dfe01.png)

**Comment by ceedubs** [comment]
Thanks for pointing this out @hagl !

I really like your idea of using `Nonempty` to express this in the types.

I also don't think that `some` and `many` are very intuitive names. Throwing some options out there:

- `zeroOrMore` / `oneOrMore`
- `listOf` / 'nonemptyListOf`

**Comment by stew** [comment]
This really blew my mind, as I learned these from scalaz where they were the opposite way. They've since been removed completely but I had to go dig back in the history to ensure I wasn't crazy :)

I decided for now to rename them to `many0` and `many1` after surveying a dozen other parser generators :)
